In [3]:
import array
a=array.array("i",[2,4,6,8])
print(a)

array('i', [2, 4, 6, 8])


In [27]:
import array as arr
a=arr.array("d",[1,2,4,5,6,7])
print(a)
print(type(a))

array('d', [1.0, 2.0, 4.0, 5.0, 6.0, 7.0])
<class 'array.array'>


In [7]:
import array as arr
c=array.array("i",[2,4,6,8,9])
print("First Element", c[0])
print("Second Element", c[1])
print("Third Element", c[2])
print("Fifth Element", c[4])
print("Fourth Element", c[-2])

First Element 2
Second Element 4
Third Element 6
Fifth Element 9
Fourth Element 8


In [8]:
import array as arr
c=array.array("i",[2,4,6,8,9])
print("Length: ", len(c))

Length:  5


In [12]:
import array as arr
c=array.array("i",[2,4,6,8,9])
c.append(10)
print(c)
c.extend([44,67])
print(c)
c.insert(1,88)
print(c)
a=arr.array("i",[1,2,4,5,6,7])
c=c+a
print(c)

array('i', [2, 4, 6, 8, 9, 10])
array('i', [2, 4, 6, 8, 9, 10, 44, 67])
array('i', [2, 88, 4, 6, 8, 9, 10, 44, 67])
array('i', [2, 88, 4, 6, 8, 9, 10, 44, 67, 1, 2, 4, 5, 6, 7])


In [18]:
import array as arr
c=array.array("i",[2,4,6,8,9])
print(c)
d=c.pop(3)
print(c)
print("Popped element: ",d)
e=c.remove(2)
print(c)
print("Removed element: ",e)
f=c.pop()
print(c)
print("Popped element: ",f)

array('i', [2, 4, 6, 8, 9])
array('i', [2, 4, 6, 9])
Popped element:  8
array('i', [4, 6, 9])
Removed element:  None
array('i', [4, 6])
Popped element:  9


In [21]:
import array as arr
a=arr.array("i",[1,2,4,5,6,7])
b=array.array("i",[2,4,6,8,9])
c=arr.array("i")
c=a+b
print(c)
c=a*3
print(c)

array('i', [1, 2, 4, 5, 6, 7, 2, 4, 6, 8, 9])
array('i', [1, 2, 4, 5, 6, 7, 1, 2, 4, 5, 6, 7, 1, 2, 4, 5, 6, 7])


In [23]:
num_list=[1,2,4,5,6,7]
num_array=arr.array("i",num_list)
print(num_array[2:])
print(num_array[:])
print(num_array[-3:-1:1])
print(num_array[-3:])

array('i', [4, 5, 6, 7])
array('i', [1, 2, 4, 5, 6, 7])
array('i', [5, 6])
array('i', [5, 6, 7])


In [35]:
a=arr.array("i",[1,2,4,5,6,7])
b=array.array("i",[2,4,6,8,9])
print(a==b)

False


In [41]:
c=array.array("i",[2,4,6,8,9])
del c
print(c)

NameError: name 'c' is not defined

In [44]:
c=array.array("i",[2,4,6,8,9])
print(2 in c)
print(10 in c)
print(2 not in c)
print(10 not in c)

True
False
False
True


In [47]:
c=array.array("i",[2,4,6,8,9])
d=c.reverse()
print(d)

None


In [25]:
a=arr.array("d",[1,2,4,5,6,7])
print("Values")
for i in a:
    print(i)
for i in a:
    print(i,end=" ")

Values
1.0
2.0
4.0
5.0
6.0
7.0
1.0 2.0 4.0 5.0 6.0 7.0 

In [33]:
a=arr.array("d",[1,2,4,5,6,7])
print("Values")
temp=0
while(temp<len(a)):
    print(a[temp])
    temp=temp+1

Values
1.0
2.0
4.0
5.0
6.0
7.0


In [28]:
import numpy as np
a=np.array([1,2,4,5,6,7])
b=np.array([10,11,9])
print(a)
print(type(a))
print(b)
print(type(b))

[1 2 4 5 6 7]
<class 'numpy.ndarray'>
[10 11  9]
<class 'numpy.ndarray'>


In [29]:
c=np.array([(1,4,6),(6,5,8)])
print(c)

[[1 4 6]
 [6 5 8]]


In [30]:
d=np.array([[1,4,6],[6,5,8]])
print(d)

[[1 4 6]
 [6 5 8]]


In [34]:
d.ndim

2

In [37]:
a=np.array([((4,6,7),(5,2,1),(10,22,45),(1,5,6))])
print(a)

[[[ 4  6  7]
  [ 5  2  1]
  [10 22 45]
  [ 1  5  6]]]


In [39]:
e=np.array([[1,4,6],[6,5,8]])
print(e.shape)

(2, 3)


In [40]:
arr=np.array([1,3,6,7,8,5,10])
res=np.where(arr==5)
print(res)

(array([5], dtype=int64),)


In [49]:
arr=np.array([1,3,6,7,8,5,10])
s=np.searchsorted(arr,3)
print(s)

1


In [50]:
a=np.array([1,3,6,7,8,5,10])
print(np.max(a))
print(np.min(a))

10
1


In [51]:
a=np.array([1,3,6,7,8,5,10])
print(np.argmax(a))
print(np.argmin(a))

6
0


In [52]:
a=np.array([1,3,6,7,8,5,10])
print(np.sqrt(a))

[1.         1.73205081 2.44948974 2.64575131 2.82842712 2.23606798
 3.16227766]


In [53]:
a=np.array([1,3,6,7,8,5,10])
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [54]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [55]:
a=np.array([[2,3],[4,5]])
b=np.array([[30,50],[40,20]])
c=a+b
print(c)

[[32 53]
 [44 25]]


In [59]:
a=np.array([[2,3],[4,5]])
b=np.array([[30,50],[40,20]])
print(a.dot(b))

[[180 160]
 [320 300]]


In [63]:
a=np.array([[2,3],[4,5]])
b=np.array([[30,50],[40,20]])
print(np.multiply(a,b))

[[ 60 150]
 [160 100]]


In [64]:
a=np.array([[2,3],[4,5]])
b=np.array([[30,50],[40,20]])
print(np.matmul(a,b))

[[180 160]
 [320 300]]


In [65]:
a=np.array([[2,3],[4,5]])
b=np.array([[30,50],[40,20]])
print(a*b)

[[ 60 150]
 [160 100]]


In [68]:
d=np.array([[30,50],[40,20]])
np.sum(d)

140

In [66]:
c=np.array([[30,50],[40,20]])
np.sum(c,axis=0)

array([70, 70])

In [67]:
c=np.array([[30,50],[40,20]])
np.sum(c,axis=1)

array([80, 60])

In [75]:
arr1=np.zeros((4),dtype=int)
print(arr1)

[0 0 0 0]


In [79]:
arr2=np.zeros((3,4),dtype=int)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [77]:
arr1=np.ones((4),dtype=int)
print(arr1)

[1 1 1 1]


In [82]:
arr2=np.ones((3,4),dtype=int)
print(arr2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
